### ISSUE TITLE
Error reading .eslintrc - Syntax error

### ISSUE THREAD

**Issue by madjam002** [gandm/language-babel#135]
Starting with a recent update, I get this:
![Imgur](http://i.imgur.com/a9N0JHw.png)

I've seen recently that there have been some commits relating to JSON parsing of `.eslintrc`, is this error because I have a YAML `.eslintrc`?

Snippet:
```
---
  parser: "babel-eslint"

  env:
    browser: true
    mocha: true
    node: true
... etc
```
