### ISSUE TITLE
Operators "span" tags enclose whitespace characters at the beginning of a line

### ISSUE THREAD

**Issue by BenoitAverty** [gandm/language-babel#226]
I have a particular setup where operators have a different font than the rest of my source code. I use the following rule in my css to apply the right style : 
```css
atom-text-editor::shadow{
    .entity.other.attribute-name {
        font-style: italic;
    }

    .lines {
      .punctuation.definition.comment,
      .keyword.operator.assignment,
      .keyword.operator.arithmetic,
      .keyword.operator.comparison,
      .keyword.operator.relational,
      .keyword.operator.spread,
      .keyword.operator.logical,
      .type.arrow.function,
      .constant.numeric {
        font-family: "Fira Code Retina";
      }
    }
}
```

This made me realize the following behavior when showing whitespace chars : 
![selection_001](https://cloud.githubusercontent.com/assets/17006335/17749030/606a225a-64bc-11e6-98dd-cd24def86f26.png)

As you can see, the whitespaces before the spread operator don't have the same font as the others.

This is easily explained by the markup : 
![selection_002](https://cloud.githubusercontent.com/assets/17006335/17749067/9482e9d2-64bc-11e6-97d4-75e7a851f53e.png)

Is this on purpose ? I understand that it makes basically no difference in most cases, but with my setup it's a bit annoying.
