### ISSUE TITLE
Parameter highlighting glitch.

### ISSUE THREAD

**Issue by phyllisstein** [gandm/language-babel#264]
Hey there! This is a minor-league whine, but I noticed that after this morning's update the highlighting rules I'd created for function parameters got a little nutty:

<img width="864" alt="screen shot 2016-10-11 at 11 33 03 am" src="https://cloud.githubusercontent.com/assets/2207980/19277098/8fbf6ed8-8fa6-11e6-81b6-c338dd8b1ec7.png">

I would have expected `stores, props, actions` to be italicized and yellow, rather than every variable in the callback.

Not sure if I was capitalizing on a preexisting bug or if this constitutes a new bug, but in the past, I was able to target parameters with this CSS:

```css
  .meta.function .variable,
  .parameters {
    color: hsl( 29, 54%, 61%);
    font-style: italic;
  }
```

...whereas now, `.meta.function .variable` seems to be a bit broader. Is there any way to either extend the `parameters` class to cover the contents of the parentheses (rather than just the parenthetical delimiters themselves) or target the parameters more specifically with existing classes?
