### ISSUE TITLE
Operators like in and of are not colored properly with one-light-syntax

### ISSUE THREAD

**Issue by j-f1** [gandm/language-babel#405]
The code here matches the operators:

[gandm/language-babel/grammars/Babel Language.json](https://github.com/gandm/language-babel/blob/f9613fb35af64be342654dc8e8288c307646441e/grammars/Babel%20Language.json#L1197-L1200) lines 1197–1200
```json
{
  "match": "(?<!\\.)\\s*+\\b(delete|in|instanceof|new|of|typeof|void|with)\\b",
  "captures": {
    "1": { "name": "keyword.operator.js" }
  }
},
```

However, `one-light-syntax` only colors certain keywords from blue to purple:

[atom/one-light-syntax/styles/syntax/javascript.less](https://github.com/atom/one-light-syntax/blob/1e06623a6c245f8cc15ac0211779385e42c380c7/styles/syntax/javascript.less#L2-L16) lines 2–16
```less
.syntax--keyword.syntax--operator {
  color: @hue-1;

  // keywords are definded in https://github.com/atom/language-javascript/blob/master/grammars/javascript.cson
  // search "instanceof" for location
  &.syntax--delete,
  // ...snip...
  &.syntax--void {
    color: @hue-3;
  }
}
```

In `language-javascript`, the name of the operator is added as a scope:

[atom/language-javascript/grammars/javascript.cson](https://github.com/atom/language-javascript/blob/65c77cc1225a2d6963c9cd5599d17a96af16aea5/grammars/javascript.cson#L960-L963) lines 960–963
```cson
{
  'match': '(?<!\\.)\\b(delete|in|of|instanceof|new|typeof|void)(?!\\s*:)\\b'
  'name': 'keyword.operator.$1.js'
}
```

Could this behavior be replicated in `language-babel`?
