### ISSUE TITLE
Literal object properties/keys has same color as strings

### ISSUE THREAD

**Issue by jvitoroc** [gandm/language-babel#463]
It's not a big deal, but this is strange:
![image](https://user-images.githubusercontent.com/25753747/34219445-56b5b824-e598-11e7-97a1-1df681a1f57c.png)
We "can't" diff between key and value
![image](https://user-images.githubusercontent.com/25753747/34219518-8ddc80ee-e598-11e7-8aa6-b0de492f5251.png)

**Comment by gandm** [comment]
By design as a key is a string in the ES spec ( or maybe a symbol). If need be you can change the colour of a property key by adding some css to your Atom `styles.less` I provide an additional scope to all object keys that have values `constant.other.object.key.js` Most themes don't colour this class but you can make it whatever colour you want.

**Comment by gandm** [comment]
e.g.
```less
atom-text-editor .syntax--constant.syntax--other.syntax--object.syntax--key.syntax--js {
  .syntax--string.syntax--unquoted.syntax--js {
    color: cyan;
  }
}
```
Gives
![image](https://user-images.githubusercontent.com/2313237/34220546-e8ca2934-e5ac-11e7-8804-c8747edfe985.png)
